//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Helpline
    {
        public string Helpline1 { get; set; }
        public bool Active { get; set; }
    }
}
