//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public int CALLID { get; set; }
        public Nullable<int> CALLERID { get; set; }
        public string Counsellor { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public Nullable<bool> ReasonADHD { get; set; }
        public Nullable<bool> ReasonAlzheimersDementia { get; set; }
        public Nullable<bool> ReasonAnxiety { get; set; }
        public Nullable<bool> ReasonBipolar { get; set; }
        public Nullable<bool> ReasonDebtPovertyUnemployment { get; set; }
        public Nullable<bool> ReasonDepression { get; set; }
        public Nullable<bool> ReasonEatingDisoirder { get; set; }
        public Nullable<bool> ReasonHIVAIDS { get; set; }
        public Nullable<bool> ReasonInformation { get; set; }
        public Nullable<bool> ReasonLossGriefLoneliness { get; set; }
        public Nullable<bool> ReasonNone { get; set; }
        public Nullable<bool> ReasonOCD { get; set; }
        public Nullable<bool> ReasonOtherIllness { get; set; }
        public Nullable<bool> ReasonPhysicalEmotionalAbuse { get; set; }
        public Nullable<bool> ReasonPostNatalDepression { get; set; }
        public Nullable<bool> ReasonPTSDTrauma { get; set; }
        public Nullable<bool> ReasonReationshipDomesticAbuse { get; set; }
        public Nullable<bool> ReasonSchizophrenia { get; set; }
        public Nullable<bool> ReasonSelfMutilation { get; set; }
        public Nullable<bool> ReasonSexualAbuseRape { get; set; }
        public Nullable<bool> ReasonSleepingDisorder { get; set; }
        public Nullable<bool> ReasonSocialPhobia { get; set; }
        public Nullable<bool> ReasonStress { get; set; }
        public Nullable<bool> ReasonSubstanceAbuse { get; set; }
        public Nullable<bool> ReasonSuicide { get; set; }
        public Nullable<bool> ReferDASGFaceToFace { get; set; }
        public Nullable<bool> ReferGP { get; set; }
        public Nullable<bool> ReferGovHospital { get; set; }
        public Nullable<bool> ReferLiteratureWebsite { get; set; }
        public Nullable<bool> ReferNone { get; set; }
        public Nullable<bool> ReferOther { get; set; }
        public Nullable<bool> ReferOtherNGOHelpline { get; set; }
        public Nullable<bool> ReferPoliceStation { get; set; }
        public Nullable<bool> ReferPrivateHospital { get; set; }
        public Nullable<bool> ReferPsychiatrist { get; set; }
        public Nullable<bool> ReferPsychologist { get; set; }
        public Nullable<bool> ReferRapeCrisis { get; set; }
        public Nullable<bool> ReferShelter { get; set; }
        public Nullable<bool> ReferSocialWorker { get; set; }
        public Nullable<bool> ReferSupportGroup { get; set; }
        public Nullable<bool> ReferTraumaCentre { get; set; }
        public string CallSummary { get; set; }
        public Nullable<bool> ReasonFrequentCaller { get; set; }
        public Nullable<bool> ReasonBullying { get; set; }
        public Nullable<bool> ReasonPregnancy { get; set; }
        public Nullable<bool> ReasonSexuality { get; set; }
        public Nullable<bool> ReferRehabilitationCentre { get; set; }
        public Nullable<bool> ReasonBorderlinePersonalityDisorder { get; set; }
        public string HelpLine { get; set; }
        public Nullable<bool> ReasonOtherReason { get; set; }
        public Nullable<bool> ReasonFollowUp { get; set; }
        public Nullable<bool> ReferUniversityStudentWellness { get; set; }
        public Nullable<bool> ReferSadagHelpLine { get; set; }
        public Nullable<bool> ReferSelfHelp { get; set; }
        public Nullable<bool> ReferUber { get; set; }
        public string DLCallTimeOfDay { get; set; }
        public string CalledOnBehalfOf { get; set; }
        public string ActionPoints { get; set; }
        public Nullable<bool> ReasonRelationshipRomanticIssues { get; set; }
        public Nullable<bool> ReasonRelationshipFamilyIssues { get; set; }
        public Nullable<bool> ReferCompanyEAP { get; set; }
        public Nullable<bool> ReferUniversitySupportServices { get; set; }
        public Nullable<int> DistressRatingBegining { get; set; }
        public Nullable<int> DistressRatingEnd { get; set; }
    }
}
