//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQL_COMMAND
    {
        public int RowNumber { get; set; }
        public Nullable<int> EventClass { get; set; }
        public string TextData { get; set; }
        public Nullable<int> SPID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public byte[] BinaryData { get; set; }
    }
}
